name: simple_kennel
description: "Runbook - Kennel management app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  intl: ^0.20.2
  pdf: ^3.11.1
  printing: ^5.13.2
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter_native_splash:
  color: "#7B5EA7"
  color_dark: "#4A3570"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
