// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oH8Cwl1NRSqu-l6vZBYxTpzibPnCdjc',
    appId: '1:997900573720:web:3427ae8a9e37554796b76d',
    messagingSenderId: '997900573720',
    projectId: 'simplekennel-1ca46',
    authDomain: 'simplekennel-1ca46.firebaseapp.com',
    storageBucket: 'simplekennel-1ca46.firebasestorage.app',
    measurementId: 'G-1F68WV5PWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclEyYglcwnhvi8C0GjPa3oTTg19MONMM',
    appId: '1:997900573720:android:3926cca67981a8dd96b76d',
    messagingSenderId: '997900573720',
    projectId: 'simplekennel-1ca46',
    storageBucket: 'simplekennel-1ca46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4LfWUQvI-InVVvWsM1ffx-JyvOlkL5g',
    appId: '1:997900573720:ios:2f8dc5a2ee8a687c96b76d',
    messagingSenderId: '997900573720',
    projectId: 'simplekennel-1ca46',
    storageBucket: 'simplekennel-1ca46.firebasestorage.app',
    iosBundleId: 'com.simplekennel.simpleKennel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4LfWUQvI-InVVvWsM1ffx-JyvOlkL5g',
    appId: '1:997900573720:ios:2f8dc5a2ee8a687c96b76d',
    messagingSenderId: '997900573720',
    projectId: 'simplekennel-1ca46',
    storageBucket: 'simplekennel-1ca46.firebasestorage.app',
    iosBundleId: 'com.simplekennel.simpleKennel',
  );
}
